### ISSUE TITLE
Automigrate fails when adding an index.

### ISSUE THREAD

**Issue by lortabac** [valderman/selda#107]
I have a migration that only adds an index to a column. Something like `[Migration foo0 foo1 pure]`, where `foo0` and `foo1` are identical, except for an index attribute.

The first time I run the migration (with `autoMigrate`), the index is added correctly. The second time the migration fails with the message:

```
SqlError "error executing query `CREATE INDEX \"ixfoo_indexed_col\" ON \"foo\" (\"indexed_col\")': ERROR:  relation \"ixfoo_indexed_col\" already exists
```

**Comment by lortabac** [comment]
I think I found out why. The index I added is not unique, and in fact I just realized that `TableInfo` only lists uniqueness constraints. Is there a reason why non-unique indexes are not taken into account?

If it's not done on purpose, I can open a PR to correct this behavior.

**Comment by lortabac** [comment]
Ok. Apparently `tryCreateTable` already takes care of creating the missing indexes. So there is no need for a migration. I'm closing this issue.

**Comment by valderman** [comment]
This is definitely a bug. The `ColumnInfo` structure should contain `colHasIndex = True` if the column has an index, unique or not. Which backend were you using when this occurred?

**Comment by lortabac** [comment]
I am using PostgreSQL.

`ColumnInfo` is correct. As far I understand, the problem is that the `diffColumn` function in `Database.Selda.Validation` does not do any check on `colHasIndex`.

Another problem I discovered is that `Database.Selda.Table.Compile.compileCreateIndex` does not check whether the index already exists. As a quick fix I added `IF NOT EXISTS`, but I don't know how standard it is. I think a more complex solution is needed for more portability.

**Comment by valderman** [comment]
The validation/migration issue was a relatively simple fix, but the index creation indeed requires a bit more thinking. Currently migrations are implemented as follows:
1. a new table is created with a temp name;
2. data is moved from the old table into the new one;
3. the old table is deleted.

As index names are based on table names, this means that index names may collide after performing several migrations. Worse, adding `IF NOT EXISTS` won't help the situation since the existence of an old index will prevent the creation of a new one, and then the old index gets dropped together with its original table.

Probably, we should remove any indices associated with the old table before creating the new one. Since every single row in the table will be traversed anyway, this shouldn't lead to any performance issues. If the migration's data conversion operation does something exotic like joining the table under migration with itself, _then_ there may be performance issues, but I'm not convinced this is anywhere near likely enough to warrant a more complicated solution.
