### ISSUE TITLE
Selda lacks multiple column indexes

### ISSUE THREAD

**Issue by TomMD** [valderman/selda#121]
Most SQL databases, including postgresql and sqlite, support indexes over multiple columns.  Selda currently lacks this support.  Is there a reason beyond basic engineering and time constraints?

**Comment by valderman** [comment]
No, there's no good reason for not having it. It used to be a bit unclear what would be a nice syntax for it, but we already have a decent syntax for PKs and uniqueness constraints spanning multiple columns so there's no reason not to just use that and add it already.

**Comment by TomMD** [comment]
I have this in #122 but made the version 1.5.0.0 because of the change in index api.  Am happy to see it merge with any version and can make the adjustment in the branch if desired.

**Comment by valderman** [comment]
I agree, bumping the type of `index` and `indexUsing` necessitates a major version bump. There's not really that much more stuff to put in there, so unless something else that needs some existing API to change crops up very soon, we'll have it out soonish. 

Fixed in 5735c0fd1a3a658178a9add1336b6275066e68db.
