### ISSUE TITLE
Support SQL UNION 

### ISSUE THREAD

**Issue by shfrmn** [valderman/selda#140]
Hi!

Thanks a lot for your work on Selda, it's really appreciated! 

Lately I was looking for a way to concatenate multiple selections of the same type and it doesn't seem possible at the moment. If there's indeed no way to do it, would it be a good idea to support `UNION` by providing `Row s a` with a `Semigroup` instance? 

```haskell
-- Example:
pets :: Query s (Row s Pet)
pets = do
  cat <- select cats
  dog <- select dogs
  pure $ cat <> dog
```

What do you think?

**Comment by valderman** [comment]
This would be quite elegant, but a bit hard to implement for `Row` the way Selda currently works under the hood since `UNION` works on queries and not expressions. However, it would certainly be possible to implement for `Query s a`:

```haskell
pets :: Query s (Row s Pet)
pets = do
  let cats = select cats
  let dogs = select dogs
  cats <> dogs
```

It's not quite as elegant, but would be easy to implement right now.

One thing to consider however, is whether that semigroup should be `UNION` or `UNION ALL`. I'm leaning towards `UNION ALL`, since (a) it feels more natural to me, and (b) you could do something like the following and the query planner would most likely still produce efficient code:

```haskell
pets :: Query s (Row s Pet)
pets = distinct $ mconcat
  [ select cats
  , select dogs
  , ...
  ]
```

Thoughts?

**Comment by valderman** [comment]
It seems I was a bit too optimistic about the semigroups; this API would unfortunately not be well-scoped since a union results in at least two inner queries (which must not be able to access any columns from the outer query).

I'm afraid we'll have to make do with something like the following API instead:
```haskell
union :: (Columns a, Columns (OuterCols a))
      => Query (Inner s) a
      -> Query (Inner s) a
      -> Query s (OuterCols a)

unionAll :: (Columns a, Columns (OuterCols a))
      => Query (Inner s) a
      -> Query (Inner s) a
      -> Query s (OuterCols a)
```
