### ISSUE TITLE
Question on prepared statements

### ISSUE THREAD

**Issue by collinpeters** [valderman/selda#177]
Sorry if this is not the right avenue. I am a non-Haskell engineer working on some systems where Haskell is deployed and Selda is used for connecting to a Postgresql database. We are enabling a [DataDog/Postgres](https://docs.datadoghq.com/database_monitoring/) integration of which one of the features is query tracking and performance. Behind the scenes it uses explain plans to help diagnose queries.

We are getting an error in the postgres logs complaining that queries that are coming from Selda cannot be processed by Datadog. The Datadog support team [sent a link](https://docs.datadoghq.com/database_monitoring/setup_postgres/troubleshooting/#queries-are-missing-explain-plans) noting that the integration does not work with prepared statements nor the extended query protocol.

I'm trying to find out if Selda is using either of these two things. From the GitHub readme I see the feature "Seamless prepared statements" but in grepping our source I can't see that this is used.

So my questions are simply
1. Are prepared statements used by default?
2. Is the Postgres [extended query protocol](https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY) used at all?
3. Are there any configuration options to control any of this on the Selda side?

**Comment by valderman** [comment]
1. Named prepared statements are only used when using [prepared](https://hackage.haskell.org/package/selda-0.5.1.0/docs/Database-Selda.html#v:prepared). However...
2. Selda uses the [libpq Haskell bindings](https://hackage.haskell.org/package/postgresql-libpq). More specifically, non-prepared statements use the [execParams](https://hackage.haskell.org/package/postgresql-libpq-0.9.4.3/docs/Database-PostgreSQL-LibPQ.html#v:execParams) function, which does indeed look like it uses the extended protocol.
3. No. If _"supplying data values as separate parameters instead of having to insert them directly into a query string"_ requires use of the extended protocol, any setting to force the simple protocol would not work with Selda. I would also advise against any solution that requires the simple protocol, considering the elevated risk of SQL injections you expose yourself to when interpolating values directly into query strings.
