### ISSUE TITLE
Natural transformation and SeldaT

### ISSUE THREAD

**Issue by phaazon** [valderman/selda#38]
In my code base, I use the `Handler` monad from `servant`. It’s basically a `ReaderT IO`. All the code of `servant` runs in such a monad. However, in order to work for other monads as well, `servant` advises you to use a natural transformation `m ~> Handler` so that you can use all the `servant` functions on your own stack.

---

My problem kicks in because of [`withSQLite`](https://hackage.haskell.org/package/selda-sqlite-0.1.5.1/docs/Database-Selda-SQLite.html). It has a constraint on its base monad, `MonadMask m`. However, if you try to implement the natural transformation `SeldaT CustomMonad :~> Handler`, you quickly see there’s a problem, because `Handler`, from `servant`, doesn’t provide you with a `MonadMask` instance.

I strongly believe there’s something related to `MonadBaseControl / MonadTransControl` here, but I cannot see what.

```haskell
type Foo = …
type Handler = ReaderT Foo IO

myNat :: SeldaT Handler :~> Handler
myNat = NT $ \selda -> do
  -- here, we’re in Handler
  withSQLite "foo.db" selda -- this must run in (MonadIO m, MonadMask m) => m: not possible here
  
  -- so the solution would be to liftIO or something like that? heeeeeelp?
```

**Comment by osa1** [comment]
Ignore natural transformations, it's just there to confuse users. What you need is to write a function like this:

```haskell
import Database.Selda
import Database.Selda.SQLite
import Servant.Server

f :: FilePath -> SeldaT IO a -> Handler a
f sqlite_path a = liftIO (withSQLite sqlite_path a)
```

Basically just run your `SeldaT` until you get `IO`, then `liftIO` it.

**Comment by phaazon** [comment]
You misread. It’s not `SeldaT IO`. It’s `SeldaT Handler`.

**Comment by valderman** [comment]
Since `Handler` uses `ExceptT e IO`, I don't believe it's possible to create a `MonadMask` instance for it. The simplest thing to do here might be to just ignore `SeldaT` and instead make `Handler` an instance of `MonadSelda`. If you don't use Selda's result caching, you only need to provide `seldaConnection` and you're good to go. Of course, you'd still need to deal with the resource handling that `MonadMask` would otherwise do for you.

If you *do* want caching however, the current API doesn't expose all the functionality necessary to create a `MonadSelda` instance that's not built on `SeldaT`. We should probably fix that for the next release.

**Comment by phaazon** [comment]
Thanks for the comprehensive answer! I’ll try to do what you suggest.

**Comment by valderman** [comment]
As of 7108ee6df7530d2a6f2f2fe3712edd78815151bf, the internal `invalidate` function of the per-process cache is exported from `Database.Selda.Backend`. This allows `MonadSelda` instances to support caching without having to be based on `SeldaT`.

**Comment by phaazon** [comment]
This seems utterly complicated for such a *trivial* need. I’m pretty confident with natural transformations, yet I don’t find a suitable solution based on `NT`. Any `servant` users around here?

**Comment by valderman** [comment]
If you want to go the NT route, you should only need to wrap the call to `withSQLite` with `liftIO`. However, that'd mean opening a new database session whenever you apply that thing, which would be extremely inefficient if you're doing this multiple times per call. Doubly so since this throws any performance gains from prepared statements (if you're using them) out the window. One (potentially ugly) solution to that problem might be to use `runSeldaT` instead of `withSQLite`, open the database once using `sqliteOpen`, and inject the resulting `SeldaConnection` into your transformation manually.

**Comment by phaazon** [comment]
I don’t know what to do about that issue since I don’t have that issue in production anymore – I refactored the code so that I don’t need that kind of interleaving.

Sould I close it?

**Comment by seanhess** [comment]
Handler has a MonadMask instance now.

**Comment by tungd** [comment]
Honestly I think we should close this. `hoistServer` is now the recommended way to use custom Monad and  it doesn't rely on Natural transformation.

**Comment by valderman** [comment]
Closing, since this seems to be a bit dated by now.
