### ISSUE TITLE
ifThenElse with nullable columns

### ISSUE THREAD

**Issue by benny-medflyt** [valderman/selda#43]
`ifThenElse` (#37) is on it's way into Selda... but it doesn't work well with common scenarios involving nullable columns.

For example:
You have a nullable integer column A, and you want to write an expression like: "If A is NULL then return the value 0, otherwise return the value of A + 1"

We need something like Opaleye's [matchNullable](https://hackage.haskell.org/package/opaleye-0.5.4.0/docs/Opaleye-Column.html#v:matchNullable)

Something like that could be implemented entirely in user-land, using `ifThenElse` together with Selda's unsafe `cast` function (to cast away the null-ness). But I believe that this is common enough that it should belong as a core function in Selda.

Should we add something like `matchNullable` to Selda? If so, what should it look like? I personally think that calling it `matchNullable` and having it look exactly like opaleye's would be good. I can maybe do a pull request

**Comment by valderman** [comment]
I agree, this seems like a common enough case that we'd want a primitive for it. Especially since the home-grown solution would involve using possibly query-breaking functionality. I think matching Opaleye would be a good thing here, and I wouldn't mind using the same name. However, since `matchNullable` is essentially `maybe` over columns, it could also be nice to give it a name that implies this connection.

There's nothing that immediately comes to mind though (`maybeCol` perhaps, but that doesn't really feel right), and either alternative would be fine by me.

**Comment by valderman** [comment]
Fixed in 152793e05f55b1b3e1bd7399bcde5583ec0c48f1.
