### ISSUE TITLE
Caching with triggers?

### ISSUE THREAD

**Issue by spontaliku-softaria** [valderman/selda#48]
Disclaimer: I do not use Selda, just evaluate second-level cache solutions for postgres.

Docs states that Selda keeps track of changes and evicts cache on quesries. But what if there is a trigger which updates/inserts/deletes some tables in the same transaction? Would Selda know about that changes?

**Comment by valderman** [comment]
No, Selda's automatic caching requires that the database is only modified using Selda, and Selda currently doesn't support triggers at all. If you need this, then Selda is probably not the right tool for your use case, at least for the foreseeable future.

**Comment by spontaliku-softaria** [comment]
Thanks for answer. Btw, do you have any idea how it should be properly done? Or is there any tools implementing it somehow?

**Comment by valderman** [comment]
I believe it would be very hard to support this use case automatically. Selda analyzes writes as they are issued and invalidates cached queries that touch any of the modified tables (fairly coarse-grained, but not too hard to get right), but this requires that whatever implements the cache (in this case, Selda) has full knowledge of queries as well updates, which is fairly improbable (to put it mildly) in the presence of triggers.

I would probably go for an application-specific caching scheme in this case, because a general solution would probably be too hard, too coarse-grained, or both. Of course, you could always just snapshot the database at periodic intervals and use that for your cache, but I suspect that's not an option.
