### ISSUE TITLE
GenTable

### ISSUE THREAD

**Issue by dmjio** [valderman/selda#5]
Was curious, is there something about a table created with `GHC.Generics` that needs to be distinct from one specified manually?
```haskell
newtype GenTable a = GenTable {gen :: Table (Relation a)}
```
If not, we could probably get rid of `GenTable`, but I might be missing something.

**Comment by valderman** [comment]
The problem with getting rid of `GenTable` is that the underlying table is parameterized over `Relation a`, which is a type family. Since multiple types `a` may map to the same `Relation a` (for instance, `data A Int` and `data B Int` map to the same relation), `Relation` can't be made injective. For this reason, `genTable` won't type check unless `a` appears somewhere in its type where it's not an argument to a type family.

To work around the annoying `gen` unpack, I'm considering adding an `IsTable` type class instead, and have all functions that work with tables be polymorphic.

**Comment by valderman** [comment]
Closing this since `GenTable` is now the _only_ kind of table in Selda.
