### ISSUE TITLE
BUG: result with unknown type oid: Oid 23

### ISSUE THREAD

**Issue by devlinzed** [valderman/selda#51]
I have a table with the following types of columns: TIMESTAMP, TEXT, INTEGER, SERIAL.  When I try to interact with the table, I get the error about Oid 23.  If I use a patched version of Selda that makes 23 an integer type in addition to 20, things work fine.  Am I using the wrong types, an incompatible version of Postgres, or something like that?  This seems like something that should work.

(Edited to note I have tried various sizes of integers on the DB-side.)

**Comment by valderman** [comment]
This should indeed work. Are you by any chance running on a 32 bit system, and does this happen regardless of the DB-side integer size? In any case, if you already have a patch for this I'd be happy to merge it. 

It'd also be good to have a test case for this, but since it involves interacting with tables created outside Selda it might be a bit hard to set up without any extra scaffolding. (Which should probably be added - interaction with tables created outside Selda is currently not really tested at all.)

**Comment by devlinzed** [comment]
Is it incorrect to create tables outside of Selda?  I know there's a mechanism to create tables, but I didn't see a way to modify them (i.e. for migrations.). I am totally new here, though.

It does happen regardless of integer size.  I used `INTEGER` at first but tried variants according to the different oids in the Postgresql documentation.  My patch made it work, but I wasn't sure if it was the right fix or not.  I can open up a pull request once I adapt it for master.

**Comment by valderman** [comment]
Hm, we probably want to add 32 bit integers explicitly rather than just shoehorn them into the existing integers, or some users may be in for a nasty surprise once they get to serials larger than 2^32. Selda presently just assumes all ints to be 64 bits, which is a valid assumption when the tables are created by Selda but not otherwise.

It should definitely be easier to just drop Selda onto an existing schema, so we may need even more types. It would also be nice with some machinery to take a look at an existing table and suggest a Selda type for it, which may tie into #50 a bit.
