### ISSUE TITLE
Updating with generics and `toRel`

### ISSUE THREAD

**Issue by reygoch** [valderman/selda#54]
Currently I have this code for updating user info :

```
updateUserQ :: User -> SeldaM Int
updateUserQ User{..} = S.update user
  (\(userId :*: _) -> userId .== literal id)
  (\( userId :*: _ ) ->
    userId :*: literal username :*: literal password :*: literal admin :*: literal dateCreated :*: literal dateModified
  )
```

Since user is generic and I can use `fromRel` to convert query result to my `User` data type I was expecting that `toRel` would work in reverse like this :

```
updateUserQ :: User -> SeldaM Int
updateUserQ u@(User{..}) = S.update user
  (\(userId :*: _) -> userId .== literal id)
  (\_ -> toRel u  )
```

But I'm getting the following error :

```
src\Cookster\Repository\PostgreSQL\Selda.hs:37:10: error:
    * Couldn't match type `UTCTime' with `Col s0 UTCTime'
      Expected type: Cols
                       s0 (Int :*: (Text :*: (Text :*: (Bool :*: (UTCTime :*: UTCTime)))))
        Actual type: Database.Selda.Generic.Relation User
    * In the expression: toRel u
      In the third argument of `S.update', namely `(\ _ -> toRel u)'
      In the expression:
        S.update
          user (\ (userId :*: _) -> userId .== literal id) (\ _ -> toRel u)
   |
37 |   (\_ -> toRel u)
   |          ^^^^^^^
```

do I have to perform some additional transformation on `toRel` result or did I miss the point here?

**Comment by valderman** [comment]
The inductive tuple produced by `toRel` are the actual, concrete values from your `User` data type, while Selda needs `Cols` of those values. Since the updated values may be an arbitrary (SQL) function over the old values, `update` needs to work with the syntax tree and not concrete values.

In principle, it should be possible to define a method `toCols :: Columns (Cols s a) => Proxy s -> a -> Cols s a` on the `Columns` class (or in a new one; either should work) which just steps through the tuple and slaps a `literal` on each element, to construct the appropriate `Cols s a` value. That proxy is extremely inelegant, but _something_ needs to fix the `s`. This could possibly fixed with injective type families, but I think that cutting off support for GHC versions without them would be a bit too harsh until the next Haskell Platform or so.

**Comment by reygoch** [comment]
@valderman can you maybe point me in the right direction of implementing this `toCols` function? I don't see how I can `map` `literal` over every value since I can't really pattern match recursively on `:*:` constructor. I've been checking out injective type families but I'm not quite sure where to start with them.

**Comment by reygoch** [comment]
I've tried the following but I'm having trouble with overlapping instances that I can't resolve:

```
class Colonize s a where
  colonize :: Proxy s -> a -> Cols s a

instance {-# OVERLAPS #-} (Colonize s b, Typeable a, Typeable b, Bounded a, Bounded b, Enum a, Enum b, Show a, Show b, Read a, Read b) => Colonize s (a :*: b) where
  colonize p (a :*: b) = literal a :*: (colonize p b)
  
instance {-# OVERLAPPABLE #-} ((Cols s a ~ Col s a), Typeable a, Bounded a, Enum a, Show a, Read a) => Colonize s a where
  colonize _ a = literal a

test :: Cols s (Relation User)
test = colonize Proxy $ toRel $ User def Admin "reygoch" "password"
```

this is the error that I get:

```
* No instance for (Bounded (Text :*: Text))
        arising from a use of `colonize'
    * In the expression: colonize Proxy
      In the expression:
        colonize Proxy $ toRel $ User def Admin "reygoch" "password"
      In an equation for `test':
          test = colonize Proxy $ toRel $ User def Admin "reygoch" "password"
   |
34 | test = colonize Proxy $ toRel $ User def Admin "reygoch" "password"
```

**Comment by reygoch** [comment]
@valderman I've managed to boil it down to this:

```
class Colonize s a where
  colonize :: Proxy s -> a -> Cols s a
  
instance (Colonize s b, SqlType a) => Colonize s (a :*: b) where
  colonize p (a :*: b) = literal a :*: (colonize p b)

instance {-# OVERLAPPABLE #-} ((Cols s a ~ Col s a), SqlType a) => Colonize s a where
  colonize _ a = literal a

test :: Cols s (Relation User)
test = colonize Proxy $ toRel $ User def Admin "reygoch" "password"
```

and now my `test` case works, but if I want to abstract this `colonize Proxy . toRel` I'm hitting some trouble:

```
toCols :: (Relational a ) => Proxy s -> a -> Cols s (Relation a)
toCols p a = colonize p $ toRel a
```

```
    * Overlapping instances for Colonize
                                  s (Database.Selda.Generic.Rel (GHC.Generics.Rep a))
        arising from a use of `colonize'
      Matching instances:
        instance [overlappable] (Cols s a ~ Col s a, SqlType a) =>
                                Colonize s a
          -- Defined at src\Cookster\Database\Utilities.hs:20:31
        instance (Colonize s b, SqlType a) => Colonize s (a :*: b)
          -- Defined at src\Cookster\Database\Utilities.hs:17:10
      (The choice depends on the instantiation of `s, a'
       To pick the first instance above, use IncoherentInstances
       when compiling the other instance declarations)
    * In the expression: colonize p
      In the expression: colonize p $ toRel a
      In an equation for `toCols': toCols p a = colonize p $ toRel a
   |
27 | toCols p a = colonize p $ toRel a
   |              ^^^^^^^^^^
```

**Comment by valderman** [comment]
At some point, GHC needs to be able to unambiguously select an instance to use. Since we don't have an appropriate `Colonize` constraint coming in, it's forced to try to make this choice right here and now, which won't work since we just don't have that information (the `s` and `a`).

To make GHC happy, we need to pass the responsibility of making this choice to the caller of the function instead, which _will_ have the necessary information. So we add an appropriate `Colonize` instance:

    toCols :: (Colonize s (Relation a), Relational a) => Proxy s -> a -> Cols s (Relation a)
    toCols p a = colonize p $ toRel a

This seems to work fine:

    data Test = Test
      { foo :: Int
      , bar :: Maybe Bool
      } deriving Generic

    test :: Cols s (Relation Test)
    test = toCols Proxy (Test 42 (Just True))

**Comment by valderman** [comment]
Closing, since this issue is no longer relevant with the new generic-centric API.
