### ISSUE TITLE
Code re-usability issues

### ISSUE THREAD

**Issue by reygoch** [valderman/selda#65]
In my project I have code that is repeated for every entity in the database. For example, getting an entity by id. e.g. `User` entity:
```
getUser :: SeldaPool -> ID User -> IO (Maybe User)
getUser pool id = do
  users <- fmap ( fmap fromRel ) $ runSelda pool $ query $ do
    user <- select D.user
    restrict ( user ! D.s_user_id .== literal id )
    pure user
  pure $ listToMaybe users
```
where  `D.user` is `gen generic_user`.

I have tried to do something like this:

```
getEntity :: ToDyn (Cols () t) => Table raw_entity -> Selector t (ID entity) -> SeldaPool -> ID entity -> IO (Maybe entity)
getEntity table selector pool id = do
  entities <- fmap ( fmap fromRel ) $ runSelda pool $ query $ do
    entity <- select table
    restrict ( entity ! selector .== literal id )
    pure entity
  pure $ listToMaybe entities
```

Which doesn't work. It does work when I remove type signature, but I have to enable `AllowAmbiguousTypes` and resulting deduced type is very unpractical:

```
 getEntity :: (Cols s t ~ Cols s a2,
                    Database.Selda.Compile.Res (Cols s a2)
                    ~
                    Database.Selda.Generic.Rel (GHC.Generics.Rep a1),
                    Database.Selda.Types.ToDyn (Cols () t),
                    Database.Selda.Types.ToDyn
                      (Database.Selda.Generic.Rel (GHC.Generics.Rep a1)),
                    Database.Selda.SqlType.SqlType a3,
                    Database.Selda.Column.Columns (Cols s a2),
                    Database.Selda.Compile.Result (Cols s a2),
                    Control.Monad.Catch.MonadMask m, Control.Monad.IO.Class.MonadIO m,
                    Control.Monad.Trans.Control.MonadBaseControl IO m,
                    Database.Selda.SQL.Insert
                      (Database.Selda.Generic.Rel (GHC.Generics.Rep a1)),
                    Database.Selda.Generic.GFromRel (GHC.Generics.Rep a1),
                    Database.Selda.Generic.GRelation (GHC.Generics.Rep a1),
                    Generic a1) =>
                   Table a2
                   -> Selector t a3
                   -> Data.Pool.Pool Database.Selda.Backend.Internal.SeldaConnection
                   -> a3
                   -> m (Maybe a1)
```

Am I missing something here or can this be material for possible future improvements in selda?

**Comment by valderman** [comment]
This is definitely one area where Selda could be more user friendly. In the meantime, you could use a predicate for your generic function instead:

```
getEntity :: ( Generic t
             , Relational t
             , Result (Cols s (Relation t))
             , Columns (Cols s (Relation t))
             , Relation t ~ Res (Cols s (Relation t))
             )
          => GenTable t
          -> (Cols s (Relation t) -> Col s Bool)
          -> IO (Maybe t)
getEntity table predicate = do
  entities <- withSQLite "foo.sqlite" $ query $ do
    entity <- select (gen table)
    restrict (predicate entity)
    return entity
  return $ fmap fromRel (listToMaybe entities)
```
Then you could use it for, for instance, users by doing the selection in the predicate:
```
data User = User
  { name :: Text
  , pass :: Text
  , uid  :: RowID
  } deriving Generic

users :: GenTable User
users = genTable "users" [uid :- autoPrimaryGen]
s_name :*: s_pass :*: s_uid = selectors (gen users)

getUser :: GenTable User -> RowID -> IO (Maybe User)
getUser t uid = getEntity t (\tbl -> tbl ! s_uid .== literal uid)
```
Requires flexible contexts and could definitely be a lot more elegant, but I guess it's better than nothing.

**Comment by reygoch** [comment]
@valderman is it possible to define something like this without using `AllowAmbiguousTypes`? In this function I don't have selector which can say what `s` is so it's quite inconvenient and I'm not very skilled with all these type constraints yet.

```
getAllEntities ::
  ( Generic t
  , Relational t
  , Relation t ~ Res (Cols s (Relation t))
  )
  => SeldaPool
  -> GenTable t
  -> IO [t]
getAllEntities pool table
  = runSelda pool (fmap fromRel <$> query (select $ gen table))
```

**Comment by valderman** [comment]
With scoped type variables (to fix the `t`), you can give the query an explicit type:

```
getAllEntities ::
  forall t.
  ( Generic t
  , Relational t
  , Result (Cols () (Relation t))
  , Columns (Cols () (Relation t))
  , Relation t ~ Res (Cols () (Relation t))
  )
 => SeldaPool
  -> GenTable t
  -> IO [t]
getAllEntities pool table
  = runSelda pool (fmap fromRel <$> query (select (gen table) :: Query () (Cols () (Relation t))))
```

We should probably take a look at what injective type families can do to get the types to play nicer, because this is just way too hacky for my taste.

**Comment by Znack** [comment]
I'd probably managed to make it works with passing directly selector, without predicate, how @reygoch tried in his first comment. Although it will only work without type signatures and only for the table itself (we could not use `fromRel` and `toRel` here, regretfully), the code is pretty straightforward:
```
getEntityBySelector table selector colVal = do
    entities <- query $ do
        entity <- select table
        restrict ((entity ! selector) .== colVal)
        return entity
    return (listToMaybe entities)
```

and then in my code for particular entity I have to write a little bit of boilerplate:
```
getUserById :: Int -> SeldaM (Maybe User)
getUserById uid =
  fmap fromRel <$> getEntityBySelector (gen usersTable) userIdSel (literal uid)
```

If I try to add type signatures, I get an error about Overlapping instances for `ToDyn`:
```
getEntityBySelector
    :: ( MonadSelda m
       , Result (Cols s a)
       , Columns (Cols s a)
       , SqlType v
       )
    => Table a
    -> Database.Selda.Selector a v
    -> Col s v
    -> m (Maybe (Res (Cols s a)))
getEntityBySelector table selector colVal = do
    entities <- query $ do
        entity <- select table
        restrict ((entity ! selector) .== colVal)
--                 ^^^^^^^^^^^^^^^^^ here we have a type error
        return entity
    return (listToMaybe entities)
```
As @valderman mentioned in #54: 
> we need to pass the responsibility of making this choice to the caller of the function instead

Although here it is not choice, because now we have overlapping instances for `ToDyn`, that is private typeclass. And I wonder how  @reygoch was able to use this typeclass in constraints in his function `getEntity` [from this comment](https://github.com/valderman/selda/issues/65#issue-289929730)? Of course it is possible to do in Selda's codebase, but I suppose the client code should also be able to contains such a generic functions :) 

If we see at GHC's inferred type of our function `getEntityBySelector`, it will be about the same as mine above, but also contains ... `ToDyn` constraint :) So this is why using function without type signature the only way to get desired behaviour now, GHC can infer this constraint, but we have no way to use it directly in our code.

Oh, last note about the Generic version of the getEntity (I mean version that accept `Relational t` and can return our custom ADT instead of columns that we have to map with `fromRel` in our code later). With the type signatures we have the same problem about overlapping instances for `ToDyn`.
If we omit the type signature, type checking will pass:
```
-- getEntityBySelectorGeneric
--     :: forall t s
--      . ( Relational t
--        , Result (Cols s (Relation t))
--        , Columns (Cols s (Relation t))
--        , Relation t ~ Res (Cols s (Relation t))
--        , SqlType (Relation t)
--        )
--     => GenTable t
--     -> Database.Selda.Selector (Relation t) (Relation t)
--     -> Col s (Relation t)
--     -> SeldaM (Maybe t)
getEntityBySelectorGeneric table selector colVal = do
    entities <- query $ do
        entity <- select (gen table)
        restrict ((entity ! selector) .== colVal)
        return entity
    return $ fmap fromRel (listToMaybe entities)
```
Although we will gen an error in runtime: 
```
λ> runDB $ getEntityBySelectorGeneric usersTable userIdSel 1

<interactive>:3:1: error:
    • Non type-variable argument
        in the constraint: Database.Selda.Generic.GRelation
                             (GHC.Generics.Rep b)
      (Use FlexibleContexts to permit this)
    • When checking the inferred type
        it :: forall (m :: * -> *) b.
              (Control.Monad.IO.Class.MonadIO m, Control.Monad.Catch.MonadMask m,
               GHC.Generics.Generic b,
               Database.Selda.Generic.GRelation (GHC.Generics.Rep b),
               Database.Selda.Generic.GFromRel (GHC.Generics.Repb),
               selda-0.2.0.0:Database.Selda.Types.ToDyn
                 (Database.Selda.Generic.Rel (GHC.Generics.Rep b)),
               selda-0.2.0.0:Database.Selda.SQL.Insert
                 (Database.Selda.Generic.Rel (GHC.Generics.Rep b)),
               Database.Selda.Generic.Rel (GHC.Generics.Rep b)
               ~ (Int
                  selda-0.2.0.0:Database.Selda.Types.:*: (Data.Text.Internal.Text
                                                          selda-0.2.0.0:Database.Selda.Types.:*: (Maybe
                                   Data.Text.Internal.Text
                                 selda-0.2.0.0:Database.Selda.Types.:*: (Maybe
          Data.Text.Internal.Text
        selda-0.2.0.0:Database.Selda.Types.:*: (time-1.8.0.2:Data.Time.Clock.Internal.UTCTime.UTCTime
                                                selda-0.2.0.0:Database.Selda.Types.:*: Bool)))))) =>
              m (Maybe b)
``` 

So is there a way to make this work somehow and also allow the client code that uses library write explicit type signatures? Maybe there is a way to export `ToDyn` without its functions so client could not declare new instances? I'm not sure can it be acceptable, I understand the unsafe nature of `ToDyn` and that it should be encapsulated, but I couldn't see alternatives now :(


Oh, and thanks for Selda, it is the nicest DSL on Haskell me and my colleagues have seen :)

**Comment by valderman** [comment]
Closing, since this issue is no longer relevant with the new generic-centric API.
