### ISSUE TITLE
More type safe RowID

### ISSUE THREAD

**Issue by reygoch** [valderman/selda#67]
I was trying to make my code more type safe and self documenting, so I did the following:

```
newtype ID a = ID { unID :: Int }
  deriving ( Eq, Show, Enum, Read, Generic )

instance Bounded (ID a) where
  minBound = ID minBound
  maxBound = ID maxBound

...

data User = User
  { userId       :: ID User
  , userType     :: UserType
  , userUsername :: Text
  , userPassword :: Text
  } deriving ( Eq, Show, Generic )

user :: Table (Relation User)
user = table "User"
  $   autoPrimary  "id"
  :*: required "type"
  :*: required "username"
  :*: required "password"

...

data Recipe = Recipe
  { recipeId               :: ID Recipe
  , recipeUserId           :: ID User
  , recipeRecipeCategoryId :: ID RecipeCategory
  , recipeName             :: Text
  , recipeDescription      :: Text
  } deriving ( Eq, Show, Generic )
```

Here it is much more obvious what `ID` is actually referencing so I'd suggest we replace current `RowID` with something like `ID a`.

Current problem that I'm having with this approach is that it doesn't work with auto incrementing keys, but that is mostly because I can't implement my own version of `autoPrimary` function because I can't import `ColName` constructor and `newCol` from `Database.Selda.Table` module.

Is this intentional or...? It might be worth using the `Internal` naming convention and making `Table` module available to devs.

**Comment by valderman** [comment]
I think we could to this, but we'd need to think about what to do with [insertWithPK](http://hackage.haskell.org/package/selda-0.1.12.1/docs/Database-Selda.html#v:insertWithPK) and other functions returning the ID of the last inserted row. I really don't like the idea of just leaving the phantom type free, since that'd reduce `ID a` from being "an identifier for an a" to "an identifier for anything, with optional documentation attached". `unsafeRowID` already lets you do this of course, but being able to de-serialize IDs are kind of a necessary evil.

One option would be to add some sort of tag to tables specifying the phantom type of their primary key, but table types probably shouldn't be made even more intimidating lightly. Another option would be to add it as a sort of tag to the type of the field and use a type family to extract it. That'd keep the API nicer, but may cause issues with inference or (even more) unreadable type errors. Any other ideas?

As for exposing `Table`, if we turn `RowID` into `ID a`, what parts of `Table` would be useful to have access to? I'm not sure that, for instance, `ColInfo` would be a great idea to dispose even with an `Internal` name, but `ColName` and `newCol` are pretty safe.

**Comment by valderman** [comment]
As of 7161c3a, generic functions all use typed identifiers, while plan relations still use `RowID`. This lets us actually enforce that a `ID User` actually refers to a user, and solves the problem with inserts.

Is this an OK solution to your problem, or do we need to figure out a way to get this into the plain relations as well?

**Comment by reygoch** [comment]
@valderman wow, this looks nice. I haven't been thinking about it much since I brought it up. I'll do some more work with selda soon so I'll report back with my experience.
