### ISSUE TITLE
Unique pair of fields

### ISSUE THREAD

**Issue by reygoch** [valderman/selda#99]
I can't figure out how to make sure that the pair of fields is unique. I this similar issue as with primary keys mentioned in #25?

**Comment by valderman** [comment]
Yep, it's pretty much the same thing. Relatively simple fix too:
1. figure out what syntax to use (perhaps something like `table "foo" [ uniqueN [ #col1, #col2] ]` since `unique` is already taken?);
2. add a `UniqueN [ColName]` constructor to the `Attribute` type;
3. update `compileCreateTable` with code generation for tuples of unique columns; and
4. add the `uniqueN` function and a test or two.

**Comment by valderman** [comment]
Issue partially fixed; validation and migration support still left to do. Currently, SQLite backend just ignores multi-column indices during table validation, and the PostgreSQL backend errors out due to now-invalid assumptions about primary keys when attempting to validate a table with multi-column uniqueness constraints.
